sudo: required
language: ruby
os: linux
addons:
  postgresql: "9.4"
rvm:
  - 2.5.0
services:
  - docker
script:
- RAILS_ENV=test bundle exec rake db:create --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec spec/* -fd
after_success:
  - sh .travis/deploy_heroku.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
